In [8]:
!nvidia-smi

Fri Aug  2 16:57:19 2024       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.84       Driver Version: 460.84       CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  GeForce RTX 208...  Off  | 00000000:02:00.0 Off |                  N/A |
| 29%   29C    P8     5W / 250W |     21MiB / 11018MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  GeForce RTX 208...  Off  | 00000000:03:00.0 Off |                  N/A |
| 30%   

: 

In [1]:
import torch
from torch import nn
torch.device('cpu'), torch.device('cuda'),torch.device('cuda:1')

(device(type='cpu'), device(type='cuda'), device(type='cuda', index=1))

In [2]:
# 查询可用GPU数量
torch.cuda.device_count()

3

In [3]:
def try_gpu(i=0):
  """如果存在，则返回gpu(i)，否则返回cpu()"""
  if torch.cuda.device_count() >= i + 1:
    return torch.device(f'cuda:{i}')
  return torch.device('cpu')

def try_all_gpus():
  devices = [torch.device(f'cuda:{i}')
             for i in range(torch.cuda.device_count())]
  return devices if devices else [torch.device['cpu']]

try_gpu(),try_gpu(10),try_all_gpus()

(device(type='cuda', index=0),
 device(type='cpu'),
 [device(type='cuda', index=0),
  device(type='cuda', index=1),
  device(type='cuda', index=2)])

In [4]:
# 查看张量所在的设备
x = torch.tensor([1,2,3])
x.device

device(type='cpu')

In [5]:
# 存储在GPU方法
X = torch.ones(2,3,device=try_gpu(1))
X

tensor([[1., 1., 1.],
        [1., 1., 1.]], device='cuda:1')

不同GPU上的张量是无法直接相加的，要先复制才能相加

In [6]:
Z = X.cuda(2)

In [7]:
print(X)
print(Z)

tensor([[1., 1., 1.],
        [1., 1., 1.]], device='cuda:1')
tensor([[1., 1., 1.],
        [1., 1., 1.]], device='cuda:2')
