# 张量
张量是矩阵的推广，实际上也就是n维数组

In [5]:
import torch
X = torch.arange(24).reshape(2,3,4)
X

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

In [9]:
A = torch.arange(20,dtype=torch.float32).reshape(5,4)
B = A.clone()
# 元素乘法
A,A+B,A*B

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([[ 0.,  2.,  4.,  6.],
         [ 8., 10., 12., 14.],
         [16., 18., 20., 22.],
         [24., 26., 28., 30.],
         [32., 34., 36., 38.]]),
 tensor([[  0.,   1.,   4.,   9.],
         [ 16.,  25.,  36.,  49.],
         [ 64.,  81., 100., 121.],
         [144., 169., 196., 225.],
         [256., 289., 324., 361.]]))

## 降维
可以通过指定轴求和，来降低张量维度

In [15]:
A_sum_axis0 = A.sum(axis=0)
A_sum_axis0, A_sum_axis0.shape

(tensor([40., 45., 50., 55.]), torch.Size([4]))

## 点积、向量积和矩阵乘法

In [18]:
# 点积
x = torch.ones(4,dtype=torch.float32)
y = torch.arange(4,dtype=torch.float32)
x,y,torch.dot(x,y)

(tensor([1., 1., 1., 1.]), tensor([0., 1., 2., 3.]), tensor(6.))

In [19]:
# 向量积Ax
A = torch.arange(20).reshape((5,4))
x = torch.arange(4)
A.shape,x.shape,torch.mv(A,x)

(torch.Size([5, 4]), torch.Size([4]), tensor([ 14,  38,  62,  86, 110]))

In [22]:
# 矩阵乘法AB
B = torch.arange(20).reshape(4,5)
torch.mm(A,B)

tensor([[ 70,  76,  82,  88,  94],
        [190, 212, 234, 256, 278],
        [310, 348, 386, 424, 462],
        [430, 484, 538, 592, 646],
        [550, 620, 690, 760, 830]])

# 范数
向量范数是将向量映射到标量的函数，其常常满足几个性质：  
1. 用常数因子缩放向量的所有元素，范数也会按照因子的绝对值缩放  
$$f(αx)=|α|f(x)$$
2. 三角不等式
$$f(x+y)<=f(x)+f(y)$$
3. 非负

欧几里得距离是一个$L_2$范数，是向量元素平方和的平方根

In [26]:
#欧几里得距离L2
u = torch.tensor([3.0,-4.0])
torch.norm(u)
# L1,元素绝对值之和
torch.abs(u).sum()
# Frobenius范数,矩阵元素平方和的平方根
torch.norm(torch.ones(4,9))

tensor(6.)

在优化问题中，目标函数往往被表达为范数

In [28]:
x = torch.arange(24).reshape((2,3,4))
len(x)

2