In [3]:
import torch

# 入门
- 张量，**一维对应向量，二维对应矩阵**，在这以上没有特殊名称，在计算机上就是多维数组。

In [4]:
x = torch.arange(12) # 创建一个行向量
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [5]:
# shape属性查看张量每个轴的长度
print(x.shape)
# x.numel可以查看元素总数
print(x.numel())

torch.Size([12])
12


In [6]:
# reshape可以在不改变元素的情况下，改变形状
X = x.reshape(3,4)
X
# 可以用x.reshape(-1,4)自动计算出行的个数，即自动计算维度

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [7]:
# 创建一个(2,3,4)的张量
torch.zeros((2,3,4))
torch.ones((2,3,4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [8]:
torch.tensor([[2,1,4,3],[1,2,3,4],[4,3,2,1]])
torch.randn(3,4)

tensor([[-1.4990,  0.6843,  0.1124,  0.4364],
        [-0.9174, -2.5735,  1.9596,  2.3481],
        [ 0.8135,  1.9500,  0.0291, -0.9291]])

# 运算符

In [9]:
x = torch.tensor([1.0, 2, 4 ,8])
torch.exp(x)

tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03])

将多个tensor连结起来,通过指定轴来进行连接
- dim = 0，就是按照形状的第一个元素来连接
- dim = 1，就是按照形状的第二个元素来连接

In [11]:
X = torch.arange(12,dtype=torch.float32).reshape((3,4))
Y = torch.tensor([[2.0,1,4,3],[1,2,3,4],[4,3,2,1]])
torch.cat((X,Y),dim=0), torch.cat((X,Y),dim=1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

# 广播
即使形状不同的张量，也可以进行元素的运算操作，会自动可扩展数组，使之具有相同的形状。

In [13]:
a = torch.arange(3).reshape((3,1))
b = torch.arange(2).reshape((1,2))
a,b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [14]:
a+b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

# 索引和切片

In [18]:
X = torch.arange(12).reshape((3,4))
X

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [20]:
X[-1], X[1:3]

(tensor([ 8,  9, 10, 11]),
 tensor([[ 4,  5,  6,  7],
         [ 8,  9, 10, 11]]))

In [22]:
X[1:3,-1], X[1:3,:]

(tensor([ 7, 11]),
 tensor([[ 4,  5,  6,  7],
         [ 8,  9, 10, 11]]))